In [ ]:
!unzip /content/drive/MyDrive/data_movie.zip -d /content/drive/MyDrive/data_movie

Archive:  /content/drive/MyDrive/data_movie.zip
   creating: /content/drive/MyDrive/data_movie/data_movie/
  inflating: /content/drive/MyDrive/data_movie/data_movie/amazon.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/disney.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/hulu.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/imdb_dataset.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/movies.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/Netflix.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/plot_details.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/ratings.csv
  inflating: /content/drive/MyDrive/data_movie/data_movie/TMDB_final.csv

In [ ]:
import pandas as pd

In [ ]:
df_imdb = pd.read_csv('/content/drive/MyDrive/data_movie/data_movie/imdb_dataset.csv')

In [ ]:
df_imdb.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Gross,cast
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,"28,341,469","['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,"134,966,411","['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,"534,858,444","['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,"57,300,000","['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,"4,360,000","['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df_imdb['Genre'] = df_imdb['Genre'].apply(lambda x: x.split(','))

In [ ]:
df_imdb.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Gross,cast
0,The Shawshank Redemption,1994,A,142 min,[Drama],9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,"28,341,469","['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175 min,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,"134,966,411","['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152 min,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,"534,858,444","['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202 min,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,"57,300,000","['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96 min,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,"4,360,000","['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df_imdb.drop("Meta_score", axis=1, inplace=True)

In [ ]:
df_imdb.dropna(inplace=True)

In [ ]:
df_imdb["Gross"] = df_imdb["Gross"].apply(lambda x: int(str(x).replace(",","")))

In [ ]:
df_imdb.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Director,Gross,cast
0,The Shawshank Redemption,1994,A,142 min,[Drama],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175 min,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152 min,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202 min,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96 min,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df_imdb.rename(columns={"Series_Title": "Title", "IMDB_Rating": "Rating"}, inplace=True)

In [ ]:
df_imdb.head()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,cast
0,The Shawshank Redemption,1994,A,142 min,[Drama],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175 min,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152 min,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202 min,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96 min,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df_imdb.rename(columns={"cast": "Cast"}, inplace=True)

In [ ]:
df_imdb.head()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
0,The Shawshank Redemption,1994,A,142 min,[Drama],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175 min,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152 min,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202 min,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96 min,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df_imdb["Runtime"] = df_imdb["Runtime"].apply(lambda x: int(x.split()[0]))

In [ ]:
df_imdb.head()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
0,The Shawshank Redemption,1994,A,142,[Drama],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df_tmdb = pd.read_csv('/content/drive/MyDrive/data_movie/data_movie/TMDB_final.csv')

In [ ]:
df_tmdb.head()

,genres,id,overview,revenue,runtime,title,vote_average,release_date,movie_id,cast
0,"['Action', 'Adventure', 'Fantasy', 'Science Fi...",19995,"In the 22nd century, a paraplegic Marine is di...",2787965087,162.0,Avatar,7.2,2009-12-10,19995,"['Zoe Saldana', 'Stephen Lang', 'Michelle Rodr..."
1,"['Adventure', 'Fantasy', 'Action']",285,"Captain Barbossa, long believed to be dead, ha...",961000000,169.0,Pirates of the Caribbean: At World's End,6.9,2007-05-19,285,"['Johnny Depp', 'Orlando Bloom', 'Keira Knight..."
2,"['Action', 'Adventure', 'Crime']",206647,A cryptic message from Bond’s past sends him o...,880674609,148.0,Spectre,6.3,2015-10-26,206647,"['Daniel Craig', 'Ben Whishaw', 'Ralph Fiennes..."
3,"['Action', 'Crime', 'Drama', 'Thriller']",49026,Following the death of District Attorney Harve...,1084939099,165.0,The Dark Knight Rises,7.6,2012-07-16,49026,"['Christian Bale', 'Anne Hathaway', 'Tom Hardy..."
4,"['Action', 'Adventure', 'Science Fiction']",49529,"John Carter is a war-weary, former military ca...",284139100,132.0,John Carter,6.1,2012-03-07,49529,"['Mark Strong', 'Willem Dafoe', 'Ciarán Hinds'..."

In [ ]:
df_tmdb=df_tmdb.drop("id", axis=1)

In [ ]:
df_tmdb.head()

,genres,overview,revenue,runtime,title,vote_average,release_date,movie_id,cast
0,"['Action', 'Adventure', 'Fantasy', 'Science Fi...","In the 22nd century, a paraplegic Marine is di...",2787965087,162.0,Avatar,7.2,2009-12-10,19995,"['Zoe Saldana', 'Stephen Lang', 'Michelle Rodr..."
1,"['Adventure', 'Fantasy', 'Action']","Captain Barbossa, long believed to be dead, ha...",961000000,169.0,Pirates of the Caribbean: At World's End,6.9,2007-05-19,285,"['Johnny Depp', 'Orlando Bloom', 'Keira Knight..."
2,"['Action', 'Adventure', 'Crime']",A cryptic message from Bond’s past sends him o...,880674609,148.0,Spectre,6.3,2015-10-26,206647,"['Daniel Craig', 'Ben Whishaw', 'Ralph Fiennes..."
3,"['Action', 'Crime', 'Drama', 'Thriller']",Following the death of District Attorney Harve...,1084939099,165.0,The Dark Knight Rises,7.6,2012-07-16,49026,"['Christian Bale', 'Anne Hathaway', 'Tom Hardy..."
4,"['Action', 'Adventure', 'Science Fiction']","John Carter is a war-weary, former military ca...",284139100,132.0,John Carter,6.1,2012-03-07,49529,"['Mark Strong', 'Willem Dafoe', 'Ciarán Hinds'..."

In [ ]:
df_tmdb=df_tmdb.drop("movie_id", axis=1)

In [ ]:
df_tmdb.dropna(inplace=True)

In [ ]:
df_tmdb["runtime"] = df_tmdb["runtime"].apply(lambda x: int(x))

In [ ]:
df_tmdb.rename(columns={"title": "Title", "vote_average": "Rating", "genres": "Genre", "overview": "Overview", "cast": "Cast", "revenue": "Gross", "runtime" : "Runtime"}, inplace=True)

In [ ]:
df_tmdb["Released_Year"] = df_tmdb["release_date"].apply(lambda x: int(x.split("-")[0]))

In [ ]:
df_tmdb.drop("release_date", axis=1, inplace=True)

In [ ]:
df_final = pd.concat([df_imdb, df_tmdb], ignore_index=True)

In [ ]:
df_final.head()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
0,The Shawshank Redemption,1994,A,142,[Drama],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,28341469,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'..."
1,The Godfather,1972,A,175,"[Crime, Drama]",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,134966411,"['Marlon Brando', 'Al Pacino', 'James Caan', '..."
2,The Dark Knight,2008,UA,152,"[Action, Crime, Drama]",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,534858444,"['Christian Bale', 'Heath Ledger', 'Aaron Eckh..."
3,The Godfather: Part II,1974,A,202,"[Crime, Drama]",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,57300000,"['Al Pacino', 'Robert De Niro', 'Robert Duvall..."
4,12 Angry Men,1957,U,96,"[Crime, Drama]",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,4360000,"['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'..."

In [ ]:
df_final.tail()

,Title,Released_Year,Certificate,Runtime,Genre,Rating,Overview,Director,Gross,Cast
5579,El Mariachi,1992,NaN,81,"['Action', 'Crime', 'Thriller']",6.6,El Mariachi just wants to play his guitar and ...,NaN,2040920,"['Carlos Gallardo', 'Jaime de Hoyos', 'Peter M..."
5580,Newlyweds,2011,NaN,85,"['Comedy', 'Romance']",5.9,A newlywed couple's honeymoon is upended by th...,NaN,0,"['Edward Burns', 'Kerry Bishé', 'Marsha Dietle..."
5581,"Signed, Sealed, Delivered",2013,NaN,120,"['Comedy', 'Drama', 'Romance', 'TV Movie']",7.0,"""Signed, Sealed, Delivered"" introduces a dedic...",NaN,0,"['Eric Mabius', 'Kristin Booth', 'Daphne Zunig..."
5582,Shanghai Calling,2012,NaN,98,[],5.7,When ambitious New York attorney Sam is sent t...,NaN,0,"['Daniel Henney', 'Eliza Coupe', 'Bill Paxton'..."
5583,My Date with Drew,2005,NaN,90,['Documentary'],6.3,Ever since the second grade when he first saw ...,NaN,0,"['Drew Barrymore', 'Brian Herzlinger', 'Corey ..."

In [ ]:
df_final.fillna("", inplace=True)

In [ ]:
df_final.to_csv("/content/drive/MyDrive/data_movie/data_movie/final_database.csv", index=False)