In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

#import numpy as np # linear algebra
#0import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

#import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
 #   for filename in filenames:
  #      print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd

In [2]:
df_ratings = pd.read_csv("/kaggle/input/datasets/organizations/grouplens/movielens-20m-dataset/rating.csv")

In [3]:
df_ratings.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [4]:
df_ratings.drop("timestamp", axis=1, inplace = True)

In [5]:
df_ratings.to_csv("ratings.csv", index=False)

In [6]:
df_movie = pd.read_csv("/kaggle/input/datasets/organizations/grouplens/movielens-20m-dataset/movie.csv")

In [7]:
df_movie.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [8]:
df_movie[["movie_name", "year"]] = df_movie["title"].str.extract(r'^(.*)\s\((\d{4})\)$')

print(df_movie.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres                   movie_name  \
0  Adventure|Animation|Children|Comedy|Fantasy                    Toy Story
1                   Adventure|Children|Fantasy                      Jumanji
2                               Comedy|Romance             Grumpier Old Men
3                         Comedy|Drama|Romance            Waiting to Exhale
4                                       Comedy  Father of the Bride Part II

   year
0  1995
1  1995
2  1995
3  1995
4  1995

In [9]:
#df_movie.drop("year", axis=1, inplace=True)

In [10]:
df_movie["genres"] = df_movie["genres"].str.split("|")

In [11]:
df_movie.head()

,movieId,title,genres,movie_name,year
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",Toy Story,1995
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]",Jumanji,1995
2,3,Grumpier Old Men (1995),"[Comedy, Romance]",Grumpier Old Men,1995
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",Waiting to Exhale,1995
4,5,Father of the Bride Part II (1995),[Comedy],Father of the Bride Part II,1995

In [12]:
df_movie.drop("title", axis=1, inplace=True)

In [13]:
df_movie.to_csv("movies.csv", index=False)

In [14]:
df_tag = pd.read_csv("/kaggle/input/datasets/organizations/grouplens/movielens-20m-dataset/tag.csv")

In [15]:
df_tag.head()

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18